### ISSUE TITLE
What versions of python are supported?

### ISSUE THREAD

**Issue by dkirkby** [fjaviersanchez/JupyterTutorial#10]
Test if the notebook works in a python 3.x environment.  If not, try and fix this.  Otherwise, document that python 2.7 is required and show how to create an appropriate conda environment for people who have installed python 3 as their default.

**Comment by fjaviersanchez** [comment]
I tried `python3.5` and `bossdata` seems to have some conflict with it. When I try to install it using `pip install bossdata` it raises an error. Same with `speclite`.

**Comment by dkirkby** [comment]
I suggest that you drop `bossdata` from the main part of the tutorial and instead read a FITS file included in the package that has whatever you need from the DR12 QSO catalog (of course, you can use `bossdata` to prepare this file and include the code for this in the package).

For `speclite`, it should be easy to get it working with py3.5 since it already passes its Travis tests under 3.x with 100% coverage.  Can you give me the steps necessary to reproduce the `pip install` error you got and I will look into it.

**Comment by fjaviersanchez** [comment]
`conda create -n py35 python=3.5 anaconda`
Once everything is installed I did:
`pip install speclite`
And this is the error I found:
`AttributeError: module 'distutils.config' has no attribute 'ConfigParser'`

**Comment by dkirkby** [comment]
It looks like this is a known problem (astropy/package-template#169) in the astropy template that is now fixed, so I just need to update speclite accordingly (dkirkby/speclite#18).
